import {
    CONTACT_NAME,
    CONTACT_JOB,
    CONTACT_DESCRIPTION,
    CONTACT_EMAIL, 
    CONTACT_FACEBOOK,
    CONTACT_PHONE,
    KEY,
    DOMAIN,
    PROJECT_ID,
    STORAGE_BUCKET,
    MESSAGING_SENDER_ID,
    APP_ID,
    MEASUREMENT_ID
} from '@env'

export const FIREBASE_KEY = KEY
export const FIREBASE_DOMAIN = DOMAIN
export const FIREBASE_PROJECT_ID = PROJECT_ID
export const FIREBASE_STORAGE_BUCKET = STORAGE_BUCKET
export const FIREBASE_MESSAGING_SENDER_ID = MESSAGING_SENDER_ID
export const FIREBASE_APP_ID = APP_ID
export const FIREBASE_MEASUREMENT_ID = MEASUREMENT_ID

export const ENV_CONTACT_NAME = CONTACT_NAME
export const ENV_CONTACT_JOB = CONTACT_JOB
export const ENV_CONTACT_PHONE = CONTACT_PHONE
export const ENV_CONTACT_EMAIL = CONTACT_EMAIL
export const ENV_CONTACT_DESCRIPTION = CONTACT_DESCRIPTION
export const ENV_CONTACT_FACEBOOK = CONTACT_FACEBOOK